[bot]
apikey = 400003297:AAEgRjhm5MBMb2OnDLirusH-URRtmhCcPYw
apikey2 = 405979615:AAHCgTVqZbe_tkbB8m3UidEm5HxlrGOaS1M
name = AssisBot
adminChatId = 11132720
delay = 0.5
[NocData]
pathNoc = Z:\NOC UNIFICADO\DB Qlik Sense\Noc Huawei version 0.01\Data_CurrentMonth2.csv
pathTtInfo = Z:\NOC UNIFICADO\DB Qlik Sense\Noc Huawei version 0.01\Data_CurrentMonthExtra2.csv
pathLista = Z:\NOC UNIFICADO\DB Qlik Sense\Noc Huawei version 0.01\Data_CurrentMonthList2.csv
ttGoal = 9500
